---
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: k8s/**/*
area/talos:
  - changed-files:
      - any-glob-to-any-file: talos/**/*
area/taskfiles:
  - changed-files:
      - any-glob-to-any-file: .taskfiles/**/*
