---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

x-env: &env
  disk: "{{.disk}}"
  job: "{{.job}}"
  node: "{{.node}}"

vars:
  ROOK_SCRIPTS_DIR: "{{.ROOT_DIR}}/.taskfiles/Rook/scripts"
  ROOK_TEMPLATES_DIR: "{{.ROOT_DIR}}/.taskfiles/Rook/templates"

tasks:

  reset:
    desc: Reset Rook
    prompt: Reset rook disk with '{{.node}}/{{.disk}}' in the '{{.cluster}}' cluster ... continue?
    cmds:
      - for: { var: cephnodes }
        task: reset-data
        vars:
          cluster: "{{.cluster}}"
          disk: '{{index (.ITEM | split ":") "_1"}}'
          node: '{{index (.ITEM | split ":") "_0"}}'
      - for: { var: cephnodes }
        task: reset-disk
        vars:
          cluster: "{{.cluster}}"
          disk: '{{index (.ITEM | split ":") "_1"}}'
          node: '{{index (.ITEM | split ":") "_0"}}'
    requires:
      vars: ["cluster", "cephnodes"]

  reset-disk:
    desc: Reset a rook disk on a node
    summary: |
      Args:
        cluster: Cluster to run command against (required)
        disk: Disk to wipe (required)
        node: Node the disk is on (required)
    cmds:
      - envsubst < <(cat {{.ROOK_TEMPLATES_DIR}}/WipeDiskJob.tmpl.yaml) | kubectl --context {{.cluster}} apply -f -
      - bash {{.ROOK_SCRIPTS_DIR}}/wait-for-job.sh {{.job}} default {{.cluster}}
      - kubectl --context {{.cluster}} wait job/{{.job}} --for condition=complete --timeout=1m
      - kubectl --context {{.cluster}} logs job/{{.job}}
      - kubectl --context {{.cluster}} delete job {{.job}}
    env: *env
    requires:
      vars: ["cluster", "disk", "node"]
    vars:
      job: wipe-disk-{{.node}}-{{.disk | replace "/" "-"}}
    preconditions:
      - test -f {{.ROOK_SCRIPTS_DIR}}/wait-for-job.sh
      - test -f {{.ROOK_TEMPLATES_DIR}}/WipeDiskJob.tmpl.yaml

  reset-data:
    desc: Reset rook data on a node
    summary: |
      Args:
        cluster: Cluster to run command against (required)
        node: Node the data is on (required)
    cmds:
      - envsubst < <(cat {{.ROOK_TEMPLATES_DIR}}/WipeDataJob.tmpl.yaml) | kubectl --context {{.cluster}} apply -f -
      - bash {{.ROOK_SCRIPTS_DIR}}/wait-for-job.sh {{.job}} default {{.cluster}}
      - kubectl --context {{.cluster}} -n default wait job/{{.job}} --for condition=complete --timeout=1m
      - kubectl --context {{.cluster}} -n default logs job/{{.job}}
      - kubectl --context {{.cluster}} -n default delete job {{.job}}
    env: *env
    requires:
      vars: ["cluster", "node"]
    vars:
      job: wipe-data-{{.node}}
    preconditions:
      - test -f {{.ROOK_SCRIPTS_DIR}}/wait-for-job.sh
      - test -f {{.ROOK_TEMPLATES_DIR}}/WipeDataJob.tmpl.yaml
